[package]
name = "brul-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
brul-utils = { workspace = true }
pollster = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
wgpu = { workspace = true }
winit = { workspace = true }
