[package]
name = "brul"
version = "0.1.0"
edition = "2024"

[dependencies]
brul-macro = { workspace = true }
brul-utils = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
